export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_FAIL = 'POST_LIST_FAIL'

export const POST_LIST_FEATURED_REQUEST = 'POST_LIST_FEATURED_REQUEST'
export const POST_LIST_FEATURED_SUCCESS = 'POST_LIST_FEATURED_SUCCESS'
export const POST_LIST_FEATURED_FAIL = 'POST_LIST_FEATURED_FAIL'
