export const TAG_LIST_REQUEST = 'TAG_LIST_REQUEST'
export const TAG_LIST_SUCCESS = 'TAG_LIST_SUCCESS'
export const TAG_LIST_FAIL = 'TAG_LIST_FAIL'

export const TAG_SINGLE_REQUEST = 'TAG_SINGLE_REQUEST'
export const TAG_SINGLE_SUCCESS = 'TAG_SINGLE_SUCCESS'
export const TAG_SINGLE_FAIL = 'TAG_SINGLE_FAIL'
